### ISSUE TITLE
Problems when exporting or importing using Dataflow profile

### ISSUE THREAD

**Issue by jgperdigon** [hungvt/MagentoVAdmin#3]
When trying to export product csv file and the extension is enabled it throws me this error: Fatal error: Call to a member function unsetChild() on a non-object in /app/code/community/VES/VAdmin/Block/Head.php on line 22 when the extension is disabled the export through data flow profile works fine.

**Comment by tboulogne** [comment]
Hello,

Same on my side. any tips ?

**Comment by dcurtise** [comment]
I'm having the same issue in Magento 1.9.0.1 - would love a solution.

**Comment by tboulogne** [comment]
Hello,

Just comment the line causing the error in the file and it works.

Thierry BOULOGNE

06 43 18 31 19

**Comment by dcurtise** [comment]
Hi Thierry,

Thanks, FYI - I had to comment out lines 12, 13, 16, 20 to get it working.

Thank for advice and support.

Kind regards,

Dave Curtis

CurtisE Digitalhttp://curtisedigital.com.au/?sig | 02 8006 0103

**Comment by tboulogne** [comment]
You're welcome 😄

Thierry BOULOGNE

06 43 18 31 19

**Comment by hungvt** [comment]
In order to resolve this problem let edit this file: app/code/community/VES/VAdmin/Block/Head.php

Change this code (line 21-23)

``` PHP
if(!Mage::getStoreConfig('vadmin/header/show_notifications')){
    $this->getLayout()->getBlock('root')->unsetChild('notifications');
}
```

To 

``` PHP
$notificationBlock = $this->getLayout()->getBlock('notifications');
if(!Mage::getStoreConfig('vadmin/header/show_notifications') && $notificationBlock){
    $this->getLayout()->getBlock('root')->unsetChild('notifications');
}
```

**Comment by dcurtise** [comment]
Thanks hungvt, I appreciate your update
